version: 1.1
kind: operation
name: build-plx-st-ai-alert-classifier-app
params:
  destination:
    connection: "docker-connection"
    value: plx-st-ai-alert-classifier-app:0.1.0
  context:
    value: "{{ globals.artifacts_path }}/plx-st-ai-alert-classifier-app"
runPatch:
  init:
    - git:
        url: "https://github.com/avivkri/plx-st-ai-alert-classifier-app"
hubRef: kaniko

